<template>
<div id="signup" class="bg-light">

<!-- Signup form -->
<b-row>
  <b-jumbotron id="signup_box" class="bg-light">
    <h1 align="center" class="topfont">Create New Account</h1>
    <b-form @submit.prevent="onSignUp" v-if="show">

      <b-form-group id="input-group-1" label-for="input-1">
        <b-form-input
          id="input-1"
          v-model="form.email"
          type="text"
          required
          placeholder="Email"
        ></b-form-input>
      </b-form-group>

      <b-form-group id="input-group-2" label-for="input-2">
        <b-form-input
          id="input-2"
          :type="passwordShow"
          v-model="form.password"
          required
          placeholder="Password"
        ></b-form-input>
      </b-form-group>

      <b-form-group>
        <b-form-checkbox
          id="checkbox-1"
          v-model="passwordShow"
          name="checkbox-1"
          value="text"
          unchecked-value="password"> Show Password
        </b-form-checkbox>
      </b-form-group>

      <b-form-group id="input-group-3" label-for="input-3">
        <b-form-input
          id="input-3"
          v-model="form.firstName"
          type="text"
          required
          placeholder="First Name"
        ></b-form-input>
      </b-form-group>
      
      <!-- checkbox for user type -->
      <b-form-group id="input-group-3" label-for="input-3">
        <b-form-input
          id="input-4"
          v-model="form.lastName"
          type="text"
          required
          placeholder="Last Name"
        ></b-form-input>
      </b-form-group>
      
      <b-form-group id="input-group-3" label-for="input-3">
          <b-form-select v-model="form.sex" :options="sexOptions" class="mb-3">
          <template v-slot:first>
            <b-form-select-option :value="null" disabled>Sex</b-form-select-option>
          </template>
        </b-form-select>
      </b-form-group>

      <!-- checkbox for user type -->
      <b-form-group id="input-group-3">
        <b-form-radio-group size="lg">
          <b-form-radio v-model="form.userType" value="s">I'm a student</b-form-radio>
          <b-form-radio v-model="form.userType" value="t">I'm a teacher</b-form-radio>
        </b-form-radio-group>
      </b-form-group>

      <!-- Buttons for submission -->
      <b-row class="justify-content-md-center">
        <b-col cols="3">
          <b-button block type="submit" variant="primary">SignUp</b-button>
        </b-col>
        <b-col align-self="end" style="font-size: 18px; text-align: right; padding: 0px" cols="6">Have a account?</b-col>
        <b-col cols="3">
          <b-button block @click="goLogin" variant="outline-secondary">LogIn</b-button>
        </b-col>
      </b-row>
      
    </b-form>
    <b-card class="mt-3" header="Form Data Result" v-if="debug">
      <pre class="m-0">{{ form }}</pre>
    </b-card>
  </b-jumbotron>
</b-row>
  </div>
</template>

<script>
import { auth, firestore } from '../firebase/app'

  export default {
    // components: {
    //   ValidationProvider
    // },
    data() {
      return {
        sexOptions: [
          {value: 'm', text: 'Male'},
          {value: 'f', text: 'Female'}
        ],
        passwordShow: 'password',
        form: {
          email: '',
          password: '',
          userType: null,
          sex: null,
        },
        show: true,
        debug: false,
        errors: [],
      }
    },
    methods: {

      // when the form submit button is pressed, check input and send the data to firebase.
      onSignUp(event) {

        // TODO: make better checks for form inputs.
        this.errors = [];
        if (this.form.email.length < 5) {
          this.errors.push('Your password is not strong enough!')
        }
        if (!this.errors.length) {
          console.log('creat user')
          event.target.classList.add('was-validated');

          // stores user email and password to firebase user authentication.
          // TODO: add email confirmation.
          auth.createUserWithEmailAndPassword(this.form.email, this.form.password).then(cred => {
            
            // populates firestore with user data when they sucessfully sign up.
            // cred.user.uid is generated by firebase and we use as unique key in firestore.
            return firestore.collection('users').doc(cred.user.uid).set({
              userType: this.form.userType,
              sex: this.form.sex,
              firstName: this.form.firstName,
              lastName: this.form.lastName,
            })
          }).then(() => {
              console.log('Created user')
              this.$router.push('/')
            }).catch((error) => {

              // TODO: replace alert calls to something more elegant
              this.errors.push(error.message);
              alert(this.errors)
            });
            alert('Created Account!')
        }
      },

      // returns to login page.
      goLogin() {
        this.$router.push('/')
      }
    }
  }
</script>

<style scoped>
.topfont {
  padding-top: 50px;
  padding-bottom: 20px;
}

#signup {
  height: 100vw;
  background-color: rgb(37, 37, 37),
}

#signup_box {
  padding-top: 20px;
  margin: auto;
  margin-top: 55px;
  width: 500px;
  text-align: left;
}
</style>